# Generated by Django 4.2.6 on 2024-04-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_image', models.ImageField(upload_to='image-uploads/')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
